#!/usr/bin/env bash

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <folder_name> <file_name>"
  exit 1
fi

FOLDER_NAME="$1"
FILE_NAME="$2"

FOLDER_PATH="./modules/${FOLDER_NAME}"
FILE_PATH="${FOLDER_PATH}/${FILE_NAME}.nix"

mkdir -p "$FOLDER_PATH"

cat > "$FILE_PATH" <<EOF
{ config, pkgs, lib, ... }:

{
  home.packages = with pkgs; [];
  programs. = {};
}
EOF

echo "Created folder: $FOLDER_PATH"
echo "Created file with template: $FILE_PATH"

